CREATE ROLE {{.User}} WITH LOGIN PASSWORD '{{.Pass}}';
CREATE DATABASE {{.Name}} OWNER {{.User}};

GRANT ALL PRIVILEGES ON DATABASE {{.Name}} TO {{.User}};
GRANT ALL PRIVILEGES ON SCHEMA {{.Schema}} TO {{.User}};

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA {{.Schema}} TO {{.User}};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA {{.Schema}} TO {{.User}};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA {{.Schema}} TO {{.User}};