DROP DATABASE IF EXISTS {{.Name}};
DO $$ 
BEGIN 
    IF EXISTS ( SELECT 1 FROM pg_roles WHERE rolname = '{{.User}}' ) 
    THEN 
        REVOKE ALL PRIVILEGES ON SCHEMA public FROM {{.User}};
        REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM {{.User}};
        REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM {{.User}};
        REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM {{.User}};
        REVOKE ALL PRIVILEGES ON SCHEMA {{.Schema}} FROM {{.User}};
        REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA {{.Schema}} FROM {{.User}};
        REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA {{.Schema}} FROM {{.User}};
        REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA {{.Schema}} FROM {{.User}};
        
    END IF; 
END $$ ;
DROP USER IF EXISTS {{.User}};
DROP ROLE IF EXISTS {{.User}};